name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches: [main]
    paths-ignore:
      - '.github/workflows/**'
      - 'docs/**'
      - '*.md'

jobs:

  codeql-analysis:
    permissions:
      actions: read
      contents: read
      security-events: write
    name: CodeQL Scan
    uses: ./.github/workflows/security_codeql.yml