name: Hello World
on: [push]
jobs:
  Hello-World-Job:
    runs-on:
      - codebuild-tdonaworth-GitHub-Runners-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - run: echo "Hello World!"
